0 == ""             // true (both convert to 0)
0 == "0"          // true ("0"-> 0)
0 == "false"       //true
null == undefined  // true (both represent "no value")
"\t\n" == 0  // true (whitespace converts to 0)
null == 0         // false (null is only equal to undefined)
null == ""        // false (null is only equal to undefined)
null == false     // false (null is only equal to undefined)
undefined == 0    // false (undefined is only equal to null)
undefined == ""   // false (undefined is only equal to null)
undefined == false // false (undefined is only equal to null)
NaN == NaN       // false (NaN is not equal to anything, including itself) 

console.log("" === false); // false (different types)
console.log(null == undefined); // true (both represent "no value")
console.log(null === undefined); // false (different types)
console.log(0 === "false"); // false (different types)
console.log(0 == "false"); // true ("false" converts to 0)
console.log("" == "0") // false (empty string is not equal to "0")